server:
  port: 8080

spring:
  application:
    name: BAPAI

  # 1. DB ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yumyum_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy

  # 2. ?? ??? ??
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 3. ?? ??? ?? (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: kjw3568@gmail.com
    password: rpchzoihscgojgbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# 4. MyBatis ??
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ssafy.bapai
  configuration:
    map-underscore-to-camel-case: true

# 5. JWT ??
***REMOVED***
  secret: ssafy_yumyum_coach_project_secret_key_should_be_very_long_1234
  expiration: 86400000 # 24??

# 6. ?? ??? ?? (OAuth2)
oauth2:
  google:
    client-id: "196920571280-p5h4odh5nai2i21fia7mjol2f8k30jsr.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:5173/oauth/callback/google"
    token-uri: "https://oauth2.googleapis.com/token"
    user-info-uri: "https://www.googleapis.com/oauth2/v2/userinfo"

  kakao:
    client-id: "c8827d0d21ee937975f06fcbaff4d89b"
    redirect-uri: "http://localhost:5173/oauth/callback/kakao"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"

  naver:
    client-id: "vYl0S5pGPeLpfNSae9fW"
    client-secret: "kiP2CE5oRn"
    redirect-uri: "http://localhost:5173/oauth/callback/naver"
    token-uri: "https://nid.naver.com/oauth2.0/token"
    user-info-uri: "https://openapi.naver.com/v1/nid/me"